/**
 * Renderer-safe mirror of the tool-name catalog in
 * `src/main/features/agentTools/schemas.ts`.
 *
 * Shared modules cannot import a main-process module because the web tsconfig
 * deliberately excludes `src/main`. The workflow-pack contract test compares
 * this list with AGENT_TOOL_NAMES + BROWSER_TOOL_NAMES so schema changes cannot
 * silently make the sanitizer stale.
 */
export const WORKFLOW_PACK_ALLOWED_TOOL_NAMES = [
  'app_state',
  'list_courses',
  'list_course_groups',
  'create_course_group',
  'rename_course_group',
  'delete_course_group',
  'set_course_group',
  'archive_course',
  'list_materials',
  'link_materials',
  'list_links',
  'list_boards',
  'read_material',
  'list_tasks',
  'create_course',
  'create_note',
  'write_file',
  'create_folder',
  'create_task',
  'update_task',
  'create_board',
  'add_page',
  'add_shapes',
  'rename_material',
  'rename_course',
  'rename_board',
  'delete_material',
  'delete_task',
  'delete_board',
  'delete_course',
  'overwrite_note',
  'edit_sheet',
  'edit_docx_text',
  'list_course_links',
  'create_course_link',
  'update_course_link',
  'delete_course_link',
  'move_material',
  'duplicate_material',
  'list_favorites',
  'add_favorite',
  'rename_favorite',
  'remove_favorite',
  'search_course',
  'remove_shapes',
  'send_highlight_to_note',
  'send_web_clip_to_note',
  'browser_tabs',
  'lms_course_page',
  'lms_new_items',
  'lms_list',
  'browser_download',
  'browser_open',
  'browser_snapshot',
  'browser_read',
  'browser_scroll',
  'browser_click',
  'browser_type',
  'browser_key',
  'browser_select',
  'browser_hover',
  'browser_back',
  'browser_forward',
  'browser_reload',
  'browser_stop',
  'browser_focus_tab',
  'browser_close_tab',
  'browser_find',
  'browser_handoff',
  'browser_submit',
  'browser_use_saved_login',
  'browser_attach_file'
] as const
