/**
 * Durable send queue for group messages (docs/phase2-community.md §4.4).
 *
 * The whole design rests on one schema decision: `messages.id` is generated by
 * the CLIENT (§2.7). That makes an insert IDEMPOTENT — the uploader may retry
 * forever, a duplicate simply conflicts on the primary key and is treated as
 * success. Without it, "retry on timeout" would mean "sometimes post twice".
 *
 * ★ ORDERING RULE on reconnect: drain the outbox BEFORE fetching `seq > local`.
 * The reverse order makes your own messages appear *after* everyone else's,
 * which reads as data loss even though nothing was lost.
 *
 * Backoff is 1s → 2s → 4s … capped at 60s, and `next_try_at` is persisted, so
 * a restart mid-backoff does not turn into a thundering retry.
 */

import type { GroupEvent } from '../../../shared/types/group-events'
import type { PendingGroupMessage } from '../../../shared/types/group'
import { MAX_OUTBOX_ATTEMPTS, type GroupRepo } from './groupRepo'

export const BACKOFF_BASE_MS = 1_000
export const BACKOFF_CAP_MS = 60_000

/** Outcome the transport reports back for one row. */
export type SendOutcome =
  | { kind: 'sent'; messageId: string; seq: number | null }
  /** Already present remotely (PK conflict) — idempotent success. */
  | { kind: 'duplicate' }
  /** Transient: offline, timeout, 5xx. Retry with backoff. */
  | { kind: 'retry'; error: string }
  /** Server said no and will keep saying no (RLS, kicked, body rejected). */
  | { kind: 'rejected'; error: string }
  /** Token bucket / rate limit — retry, but not before `retryAfter` seconds. */
  | { kind: 'rate-limited'; error: string; retryAfter: number }

export interface OutboxUploaderDeps {
  repo: GroupRepo
  /** Performs the actual insert. Must never throw — return an outcome. */
  send: (message: PendingGroupMessage) => Promise<SendOutcome>
  emit: (groupId: string, event: GroupEvent) => void
  /** False while signed-out / offline: drain becomes a no-op. */
  canSend: () => boolean
  now?: () => number
  schedule?: (fn: () => void, ms: number) => NodeJS.Timeout
  maxAttempts?: number
}

export interface OutboxUploader {
  /** Wake the queue. Safe to call from anywhere, coalesces concurrent drains. */
  wake(): void
  /** Drains once and resolves when the pass is done (used by reconnect). */
  drain(): Promise<void>
  dispose(): void
}

/**
 * Exponential backoff with a cap. Exported for tests — the delay curve is part
 * of the contract, not an implementation detail.
 */
export function backoffMs(attempts: number, base = BACKOFF_BASE_MS): number {
  const exponent = Math.max(0, attempts)
  return Math.min(BACKOFF_CAP_MS, base * 2 ** exponent)
}

/** Maps a send outcome + attempt count to the next persisted queue state. */
export function nextOutboxState(
  outcome: SendOutcome,
  attempts: number,
  maxAttempts = MAX_OUTBOX_ATTEMPTS
): 'sent' | 'retry' | 'failed' {
  switch (outcome.kind) {
    case 'sent':
    case 'duplicate':
      return 'sent'
    case 'rejected':
      return 'failed'
    case 'retry':
    case 'rate-limited':
      // attempts is the count BEFORE this failure; the +1 is this one.
      return attempts + 1 >= maxAttempts ? 'failed' : 'retry'
  }
}

export function createOutboxUploader(
  deps: OutboxUploaderDeps
): OutboxUploader {
  const now = deps.now ?? (() => Date.now())
  const schedule =
    deps.schedule ??
    ((fn: () => void, ms: number) => {
      const timer = setTimeout(fn, ms)
      timer.unref?.()
      return timer
    })
  const maxAttempts = deps.maxAttempts ?? MAX_OUTBOX_ATTEMPTS

  let draining: Promise<void> | null = null
  let wakeTimer: NodeJS.Timeout | null = null
  let disposed = false

  function armWake(delayMs: number): void {
    if (disposed || wakeTimer !== null) return
    wakeTimer = schedule(() => {
      wakeTimer = null
      void runDrain()
    }, delayMs)
  }

  async function sendOne(row: PendingGroupMessage): Promise<number | null> {
    deps.repo.markSending(row.localId)
    const outcome = await deps.send(row)
    const decision = nextOutboxState(outcome, row.attempts, maxAttempts)

    if (decision === 'sent') {
      deps.repo.markSent(row.localId)
      if (outcome.kind === 'sent') {
        deps.emit(row.groupId, {
          type: 'local-echo-settled',
          localId: row.localId,
          messageId: outcome.messageId,
          seq: outcome.seq ?? 0
        })
      } else {
        // Duplicate: the real row already exists and will arrive (or already
        // did) via broadcast, so settling against our own id is correct.
        deps.emit(row.groupId, {
          type: 'local-echo-settled',
          localId: row.localId,
          messageId: row.localId,
          seq: 0
        })
      }
      return null
    }

    const error =
      outcome.kind === 'sent' || outcome.kind === 'duplicate'
        ? ''
        : outcome.error

    if (decision === 'failed') {
      deps.repo.markFailed(row.localId, error)
      deps.emit(
        row.groupId,
        outcome.kind === 'rate-limited'
          ? {
              type: 'local-echo-failed',
              localId: row.localId,
              reason: 'rate-limit',
              retryAfter: outcome.retryAfter
            }
          : {
              type: 'local-echo-failed',
              localId: row.localId,
              reason: outcome.kind === 'rejected' ? 'rejected' : 'network'
            }
      )
      return null
    }

    const waitMs =
      outcome.kind === 'rate-limited'
        ? Math.max(outcome.retryAfter * 1000, backoffMs(row.attempts))
        : backoffMs(row.attempts)
    deps.repo.markRetry(
      row.localId,
      error,
      new Date(now() + waitMs).toISOString()
    )
    return waitMs
  }

  async function runDrain(): Promise<void> {
    if (disposed || !deps.canSend()) return

    let nextWait: number | null = null
    for (const row of deps.repo.claimable(new Date(now()).toISOString())) {
      if (disposed || !deps.canSend()) break
      try {
        const wait = await sendOne(row)
        if (wait !== null) {
          nextWait = nextWait === null ? wait : Math.min(nextWait, wait)
          // A transient failure means the network is unhappy; stop hammering
          // the rest of the queue in this pass.
          break
        }
      } catch (error) {
        // `send` is contractually total, but a thrown error must not strand
        // the row in 'sending' forever.
        console.error('[group] outbox send threw', error)
        deps.repo.markRetry(
          row.localId,
          error instanceof Error ? error.message : 'unknown',
          new Date(now() + backoffMs(row.attempts)).toISOString()
        )
        nextWait = backoffMs(row.attempts)
        break
      }
    }
    if (nextWait !== null) armWake(nextWait)
  }

  function start(): Promise<void> {
    if (draining !== null) return draining
    draining = runDrain().finally(() => {
      draining = null
    })
    return draining
  }

  return {
    wake: () => {
      void start()
    },
    drain: () => start(),
    dispose: () => {
      disposed = true
      if (wakeTimer !== null) {
        clearTimeout(wakeTimer)
        wakeTimer = null
      }
    }
  }
}
