import { useState } from 'react'
import type { LearningDraft, LearningRun } from '../../../../shared/types/learning'

export function learningDraftIsSaveable(draft: LearningDraft): boolean {
  return (draft.artifacts?.length ?? 0) + (draft.articles?.length ?? 0) + (draft.words?.length ?? 0) + (draft.wordUpdates?.length ?? 0) > 0
    && (draft.words ?? []).every(word => word.surface.trim() && word.sentence.trim() && word.sourceRef.quote.trim() && word.sourceRef.quote.includes(word.surface) && word.sourceRef.quote.includes(word.sentence))
    && (draft.artifacts ?? []).every(artifact => artifact.title.trim() && (artifact.kind === 'quiz'
    ? artifact.questions.length > 0 && artifact.questions.every(question => question.prompt.trim() && (question.type === 'short-answer' ? (question.modelAnswer ?? question.answer).trim() : question.answer.trim()) && (question.type !== 'choice' || ((question.options?.length ?? 0) >= 2 && question.options?.every(option => option.text.trim()) && question.options?.some(option => option.id === question.answer))))
    : artifact.kind === 'cards' ? artifact.cards.length > 0 && artifact.cards.every(card => card.front.trim() && card.back.trim()) : artifact.markdown.trim()))
}

export function LearningDraftPreview({ run, pending, onSave, onCancel }: { run: LearningRun; pending: boolean; onSave: (draft: LearningDraft) => void; onCancel: () => void }): JSX.Element | null {
  const [draft, setDraft] = useState<LearningDraft>(() => structuredClone(run.draft ?? { version: 1 }))
  if (!run.draft) return null
  return <section className="learning-import-preview" aria-label="학습 자료 변환 미리보기"><div className="learning-section-heading"><div><p className="learning-eyebrow">PREVIEW BEFORE SAVING</p><h2>이렇게 학습 자료로 바꿔요</h2></div><span className="learning-pill">미리보기</span></div><p className="learning-muted">문제와 답, 카드 내용을 확인하고 고칠 수 있어요. 저장하면 새 자료가 만들어지고 원본은 그대로 남습니다.</p>
    {(draft.words ?? []).map((word, index) => <fieldset className="learning-preview-word" key={index}><legend>단어 {index + 1}</legend><div className="learning-form-row">
      {(['surface', 'lemma', 'partOfSpeech', 'pronunciation'] as const).map(field => <label className="learning-field" key={field}><span>{field === 'surface' ? '선택한 단어·표현' : field === 'lemma' ? '원형·표현' : field === 'partOfSpeech' ? '품사' : '발음'}</span><input aria-label={field === 'surface' ? '선택한 단어·표현' : field === 'lemma' ? '원형·표현' : field === 'partOfSpeech' ? '품사' : '발음'} className="text-field" value={word[field] ?? ''} disabled={pending} onChange={event => setDraft(current => { const next = structuredClone(current); next.words![index]![field] = event.target.value; return next })} /></label>)}
    </div><label className="learning-field"><span>단어 뜻</span><textarea aria-label="단어 뜻" value={word.meaning ?? ''} disabled={pending} onChange={event => setDraft(current => { const next = structuredClone(current); next.words![index]!.meaning = event.target.value; return next })} /></label><blockquote className="learning-word-example"><p>{word.sentence}</p><small>원문 예문 · {word.sourceRef.title ?? word.sourceRef.relPath ?? '저장된 글'}</small></blockquote></fieldset>)}
    {(draft.artifacts ?? []).map((artifact, artifactIndex) => <div className="learning-preview-artifact" key={artifactIndex}>
      <label className="learning-field"><span>자료 제목</span><input aria-label="자료 제목" className="text-field" value={artifact.title} disabled={pending} onChange={event => setDraft(current => { const next = structuredClone(current); next.artifacts![artifactIndex]!.title = event.target.value; return next })} /></label>
      {artifact.kind === 'quiz' && artifact.questions.map((question, index) => <div className="learning-preview-question" key={question.id}><strong>문제 {index + 1}</strong><label className="learning-field"><span>질문</span><textarea aria-label="질문" value={question.prompt} disabled={pending} onChange={event => setDraft(current => { const next = structuredClone(current); const value = next.artifacts![artifactIndex]!; if (value.kind === 'quiz') value.questions[index]!.prompt = event.target.value; return next })} /></label>
        {question.type === 'choice' && question.options?.map((option, optionIndex) => <label className="learning-field" key={option.id}><span>선택지 {optionIndex + 1}</span><input aria-label={`선택지 ${optionIndex + 1}`} className="text-field" disabled={pending} value={option.text} onChange={event => setDraft(current => { const next = structuredClone(current); const value = next.artifacts![artifactIndex]!; if (value.kind === 'quiz') value.questions[index]!.options![optionIndex]!.text = event.target.value; return next })} /></label>)}
        <label className="learning-field"><span>{question.type === 'short-answer' ? '모범 답안' : '정답'}</span>{question.type === 'choice' ? <select aria-label="정답" value={question.answer} disabled={pending} onChange={event => setDraft(current => { const next = structuredClone(current); const value = next.artifacts![artifactIndex]!; if (value.kind === 'quiz') value.questions[index]!.answer = event.target.value; return next })}><option value="">정답을 확인하세요</option>{question.options?.map(option => <option value={option.id} key={option.id}>{option.text}</option>)}</select> : <textarea aria-label={question.type === 'short-answer' ? '모범 답안' : '정답'} value={question.type === 'short-answer' ? (question.modelAnswer ?? question.answer) : question.answer} disabled={pending} onChange={event => setDraft(current => { const next = structuredClone(current); const value = next.artifacts![artifactIndex]!; if (value.kind === 'quiz') { const target = value.questions[index]!; target.answer = event.target.value; if (target.type === 'short-answer') target.modelAnswer = event.target.value } return next })} />}</label>
        <label className="learning-field"><span>해설</span><textarea aria-label="해설" value={question.explanation} disabled={pending} onChange={event => setDraft(current => { const next = structuredClone(current); const value = next.artifacts![artifactIndex]!; if (value.kind === 'quiz') value.questions[index]!.explanation = event.target.value; return next })} /></label>
      </div>)}
      {artifact.kind === 'cards' && artifact.cards.map((card, index) => <div className="learning-preview-card" key={card.id}><strong>카드 {index + 1}</strong><div className="learning-form-row">{(['front', 'back'] as const).map(face => <label className="learning-field" key={face}><span>{face === 'front' ? '앞면' : '뒷면'}</span><textarea aria-label={face === 'front' ? '앞면' : '뒷면'} value={card[face]} disabled={pending} onChange={event => setDraft(current => { const next = structuredClone(current); const value = next.artifacts![artifactIndex]!; if (value.kind === 'cards') value.cards[index]![face] = event.target.value; return next })} /></label>)}</div></div>)}
      {artifact.kind === 'summary' && <label className="learning-field"><span>정리 내용</span><textarea aria-label="정리 내용" rows={8} value={artifact.markdown} disabled={pending} onChange={event => setDraft(current => { const next = structuredClone(current); const value = next.artifacts![artifactIndex]!; if (value.kind === 'summary') value.markdown = event.target.value; return next })} /></label>}
    </div>)}
    {!learningDraftIsSaveable(draft) && <p className="learning-error" role="alert">빈 질문·답이나 빠진 정답, 원문에 없는 표현을 먼저 확인해 주세요.</p>}
    <footer className="dialog-actions"><button className="button button--secondary" type="button" disabled={pending} onClick={onCancel}>변환 취소</button><button className="button button--primary" type="button" disabled={pending || !learningDraftIsSaveable(draft)} onClick={() => onSave(draft)}>{pending ? '자료 저장 중…' : '새 학습 자료로 저장'}</button></footer>
  </section>
}
